defaults: &defaults
  adapter: postgresql
  username: postgres
  password: 
  reconnect: true
  pool: 5
  wait_timeout: 5

development:
  database: groundzero_development
  host: localhost
  <<: *defaults

test:
  database: groundzero_test
  host: localhost
  <<: *defaults
  
production:
  database: groundzero_production
  host: localhost
  <<: *defaults